import { CourseData } from '../../project/src/types';

export const MOCK_COURSES: CourseData[] = [
  {
    id: '1',
    title: 'Introduction to Web Development',
    description: 'Learn the fundamentals of web development with HTML, CSS, and JavaScript. This comprehensive course will take you from beginner to creating your first interactive websites.',
    coverImage: 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    createdAt: new Date(2023, 10, 15).toISOString(),
    updatedAt: new Date(2023, 11, 5).toISOString(),
    status: 'published',
    duration: '8 weeks',
    enrolledStudents: 345,
    completionRate: 78,
  },
  {
    id: '2',
    title: 'Data Science Fundamentals with Python',
    description: 'Master data analysis, visualization, and machine learning with Python. Learn hands-on techniques for extracting insights from real-world datasets.',
    coverImage: 'https://images.pexels.com/photos/574070/pexels-photo-574070.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    createdAt: new Date(2023, 9, 20).toISOString(),
    updatedAt: new Date(2023, 10, 10).toISOString(),
    status: 'published',
    duration: '10 weeks',
    enrolledStudents: 289,
    completionRate: 65,
  },
  {
    id: '3',
    title: 'Mobile App Development with React Native',
    description: 'Build cross-platform mobile applications using React Native. From setup to deployment, learn to create native experiences for iOS and Android.',
    coverImage: 'https://images.pexels.com/photos/3585048/pexels-photo-3585048.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    createdAt: new Date(2023, 11, 3).toISOString(),
    updatedAt: new Date(2023, 11, 3).toISOString(),
    status: 'draft',
    duration: '12 weeks',
    enrolledStudents: 0,
    completionRate: 0,
  },
  {
    id: '4',
    title: 'Advanced JavaScript Patterns and Practices',
    description: 'Take your JavaScript skills to the next level with advanced patterns, performance optimization, and modern best practices for professional development.',
    coverImage: 'https://images.pexels.com/photos/1181325/pexels-photo-1181325.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    createdAt: new Date(2023, 8, 25).toISOString(),
    updatedAt: new Date(2023, 9, 18).toISOString(),
    status: 'published',
    duration: '6 weeks',
    enrolledStudents: 192,
    completionRate: 82,
  },
  {
    id: '5',
    title: 'UX/UI Design Principles',
    description: 'Learn the core principles of user experience and interface design. From wireframing to prototyping, master the tools and techniques for creating intuitive user experiences.',
    coverImage: 'https://images.pexels.com/photos/196645/pexels-photo-196645.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    createdAt: new Date(2023, 10, 9).toISOString(),
    updatedAt: new Date(2023, 10, 9).toISOString(),
    status: 'review',
    duration: '8 weeks',
    enrolledStudents: 48,
    completionRate: 25,
  },
  {
    id: '6',
    title: 'DevOps and Cloud Infrastructure',
    description: 'Master the DevOps lifecycle and cloud infrastructure deployment. Learn containerization, CI/CD pipelines, and infrastructure as code for modern application delivery.',
    coverImage: 'https://images.pexels.com/photos/325229/pexels-photo-325229.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
    createdAt: new Date(2023, 7, 15).toISOString(),
    updatedAt: new Date(2023, 8, 20).toISOString(),
    status: 'published',
    duration: '10 weeks',
    enrolledStudents: 176,
    completionRate: 58,
  },
];